name: code_filter
text_field: text
pipeline:
    # - name: text_len_filter
    #   kwargs:
    #       text_field: text
    #       lower_bound: 32 # 2 ** 5
    #       upper_bound: 262144 # 2 ** 18
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.410874
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.458819
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.482967
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.502260
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.519383
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.534871
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.549653
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.564426
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.579345
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.595073
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.611199
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.627682
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.645243
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.664026
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.682176
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.699211
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.714664
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.728193
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_auto5L_combined
          lower_bound: 0.740484
