name: code_filter
text_field: text
pipeline:
    - name: text_len_filter  # p1-p99
      step: invalid_length
      kwargs:
          text_field: text
          lower_bound: 290
          upper_bound: 93816
    - name: float_filter
      step: quality_p00
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.133482
    - name: float_filter
      step: quality_p05
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.162949
    - name: float_filter
      step: quality_p10
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.179828
    - name: float_filter
      step: quality_p15
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.192012
    - name: float_filter
      step: quality_p20
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.201592
    - name: float_filter
      step: quality_p25
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.208627
    - name: float_filter
      step: quality_p30
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.214198
    - name: float_filter
      step: quality_p35
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.219470
    - name: float_filter
      step: quality_p40
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.225070
    - name: float_filter
      step: quality_p45
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.230754
    - name: float_filter
      step: quality_p50
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.236662
    - name: float_filter
      step: quality_p55
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.242866
    - name: float_filter
      step: quality_p60
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.249028
    - name: float_filter
      step: quality_p65
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.255239
    - name: float_filter
      step: quality_p70
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.261856
    - name: float_filter
      step: quality_p75
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.269242
    - name: float_filter
      step: quality_p80
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.277609
    - name: float_filter
      step: quality_p85
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.287817
    - name: float_filter
      step: quality_p90
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.303023
    - name: float_filter
      step: quality_p95
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 1000
