name: filter_out_bad_paths
text_field: text
pipeline: 
  - name: deny_list_filter
    kwargs:
      attribute_field: metadata.Source-File
      on_null: remove
      deny_list_file: "/home/ec2-user/extracted_pdf_paths_take48_take51.txt"