name: code_filter
text_field: text
pipeline:
    - name: text_len_filter  # p1-p99
      kwargs:
          text_field: text
          lower_bound: 37
          upper_bound: 28792
    - name: float_filter  # p5
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.271901
    - name: float_filter  # p10
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.319328
    - name: float_filter  # p15
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.365961
    - name: float_filter  # p20
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.411031
    - name: float_filter  # p25
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.444102
    - name: float_filter  # p30
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.465908
    - name: float_filter  # p35
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.482977
    - name: float_filter  # p40
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.496932
    - name: float_filter  # p45
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.511548
    - name: float_filter  # p50
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.526133
    - name: float_filter  # p55
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.542411
    - name: float_filter  # p60
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.559984
    - name: float_filter  # p65
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.579147
    - name: float_filter  # p70
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.598734
    - name: float_filter  # p75
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.619306
    - name: float_filter  # p80
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.639686
    - name: float_filter  # p85
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.660810
    - name: float_filter  # p90
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.683311
    - name: float_filter  # p95
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.708048
