name: code_filter
text_field: text
pipeline:
    - name: text_len_filter  # p1-p99
      step: invalid_length
      kwargs:
          text_field: text
          lower_bound: 58
          upper_bound: 75765
    - name: float_filter
      step: quality_p00
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.289221
    - name: float_filter
      step: quality_p05
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.391217
    - name: float_filter
      step: quality_p10
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.452659
    - name: float_filter
      step: quality_p15
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.480187
    - name: float_filter
      step: quality_p20
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.495135
    - name: float_filter
      step: quality_p25
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.501881
    - name: float_filter
      step: quality_p30
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.509268
    - name: float_filter
      step: quality_p35
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.516547
    - name: float_filter
      step: quality_p40
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.524003
    - name: float_filter
      step: quality_p45
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.532741
    - name: float_filter
      step: quality_p50
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.541860
    - name: float_filter
      step: quality_p55
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.551965
    - name: float_filter
      step: quality_p60
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.563318
    - name: float_filter
      step: quality_p65
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.576205
    - name: float_filter
      step: quality_p70
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.589547
    - name: float_filter
      step: quality_p75
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.604857
    - name: float_filter
      step: quality_p80
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.624160
    - name: float_filter
      step: quality_p85
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.646316
    - name: float_filter
      step: quality_p90
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.675413
