name: code_filter
text_field: text
pipeline:
    - name: text_len_filter  # p1-p99
      step: invalid_length
      kwargs:
          text_field: text
          lower_bound: 34
          upper_bound: 100248
    - name: float_filter
      step: quality_p00
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.284834
    - name: float_filter
      step: quality_p05
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.314122
    - name: float_filter
      step: quality_p10
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.345011
    - name: float_filter
      step: quality_p15
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.387905
    - name: float_filter
      step: quality_p20
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.436992
    - name: float_filter
      step: quality_p25
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.459134
    - name: float_filter
      step: quality_p30
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.471326
    - name: float_filter
      step: quality_p35
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.478710
    - name: float_filter
      step: quality_p40
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.486514
    - name: float_filter
      step: quality_p45
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.493101
    - name: float_filter
      step: quality_p50
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.501047
    - name: float_filter
      step: quality_p55
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.509647
    - name: float_filter
      step: quality_p60
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.518242
    - name: float_filter
      step: quality_p65
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.530987
    - name: float_filter
      step: quality_p70
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.545038
    - name: float_filter
      step: quality_p75
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.564287
    - name: float_filter
      step: quality_p80
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.590786
    - name: float_filter
      step: quality_p85
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.617901
    - name: float_filter
      step: quality_p90
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.659885
