name: code_filter
text_field: text
pipeline:
    - name: text_len_filter  # p1-p99
      kwargs:
          text_field: text
          lower_bound: 28
          upper_bound: 19800
    - name: float_filter  # p5
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.347103
    - name: float_filter  # p10
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.373721
    - name: float_filter  # p15
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.394005
    - name: float_filter  # p20
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.411025
    - name: float_filter  # p25
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.426002
    - name: float_filter  # p30
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.440262
    - name: float_filter  # p35
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.453355
    - name: float_filter  # p40
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.466794
    - name: float_filter  # p45
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.481079
    - name: float_filter  # p50
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.495739
    - name: float_filter  # p55
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.510790
    - name: float_filter  # p60
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.527652
    - name: float_filter  # p65
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.545995
    - name: float_filter  # p70
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.566555
    - name: float_filter  # p75
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.589164
    - name: float_filter  # p80
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.614251
    - name: float_filter  # p85
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.641552
    - name: float_filter  # p90
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.671708
    - name: float_filter  # p95
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.708644
