name: html
text_field: text
pipeline:
    - name: gzip_annotator
      kwargs:
          text_field: text
          anno_field: gzip

    - name: readibility_annotator
      kwargs:
          text_field: text
          output_field: readability
