name: jupyter_notebook
text_field: text
pipeline:
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.403606
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.435170
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.457017
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.474511
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.490190
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.504631
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.518586
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.532405
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.546321
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.560316
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.574490
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.588739
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.603216
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.617757
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.632331
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.646877
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.661498
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.676359
    - name: float_filter
      kwargs:
          float_field: metadata.qc_stack_edu_python_combined
          lower_bound: 0.694021
