name: code_classifier
text_field: text
pipeline:
  - name: ultrafineweb_annotator
      kwargs:
        text_field: text
        anno_field: metadata.uf_text
  - name: fasttext_annotator
    kwargs:
      fast_text_file: ft_classifiers/code_classifier_python.bin
      text_field: metadata.uf_text
      output_field: metadata.code_quality
