name: perl_code_classifier
text_field: text
pipeline:
    - name: gzip_annotator
      kwargs:
          text_field: text
          anno_field: metadata.gzip_compression_ratio

    - name: ultrafineweb_annotator
      kwargs:
          text_field: text
          output_field: metadata.stack_edu_redux
          max_text_length: 10000
          fast_text_file: /mnt/raid0/ai2-llm/classifiers/code-quality/trained_models/fasttext/stack_edu_redux_ultrafine_bin5/Perl/model.bin
    - name: linear_transform_annotator
      kwargs:
          features:
              - field: metadata.stack_edu_redux.__label__bin1
                weight: -0.411873
              - field: metadata.stack_edu_redux.__label__bin2
                weight: -0.131041
              - field: metadata.stack_edu_redux.__label__bin3
                weight: 0.090745
              - field: metadata.stack_edu_redux.__label__bin4
                weight: 0.339222
              - field: metadata.stack_edu_redux.__label__bin5
                weight: 0.112717
          bias: 0.40674
          output_field: metadata.stack_edu_redux_combined
