name: systemverilog_code_classifier
text_field: text
pipeline:
    - name: gzip_annotator
      kwargs:
          text_field: text
          anno_field: metadata.gzip_compression_ratio

    - name: ultrafineweb_annotator
      kwargs:
          text_field: text
          output_field: metadata.stack_edu_redux
          max_text_length: 10000
          fast_text_file: /mnt/raid0/ai2-llm/classifiers/code-quality/trained_models/fasttext/stack_edu_redux_ultrafine_bin5/SystemVerilog/model.bin
    - name: linear_transform_annotator
      kwargs:
          features:
              - field: metadata.stack_edu_redux.__label__bin1
                weight: -0.242712
              - field: metadata.stack_edu_redux.__label__bin2
                weight: 0.013693
              - field: metadata.stack_edu_redux.__label__bin3
                weight: 0.264104
              - field: metadata.stack_edu_redux.__label__bin4
                weight: 0.509624
              - field: metadata.stack_edu_redux.__label__bin5
                weight: -0.545642
          bias: 0.240281
          output_field: metadata.stack_edu_redux_combined
