name: quality_classifier
text_field: text
pipeline:
  - name: ultrafineweb_annotator
    kwargs:
      text_field: text
      output_field: metadata.ultrafineweb_quality
      max_text_length: 4000
      fast_text_file: /home/ec2-user/datamap-rs/configs/all_dressed/ft_classifiers/ultrafineweb.bin
      tokenizer_path: /home/ec2-user/datamap-rs/configs/all_dressed/tokenizers/deepseek_v2.json 