name: code_filter
text_field: text
pipeline:
    - name: text_len_filter
      kwargs:
          text_field: text
          lower_bound: 32 # 2 ** 5
          upper_bound: 262144 # 2 ** 18
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.122327
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.238477
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.257348
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.296064
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.339435
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.378881
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.411976
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.438697
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.460170
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.478040
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.493590
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.507927
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.523554
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.540936
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.560588
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.583107
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.609519
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.641033
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.679378
