name: code_filter
text_field: text
pipeline:
    - name: text_len_filter
      kwargs:
          text_field: text
          lower_bound: 32 # 2 ** 5
          upper_bound: 262144 # 2 ** 18
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.260485
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.285468
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.318687
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.352007
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.381987
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.407684
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.429596
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.448613
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.465492
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.480682
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.494386
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.506914
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.521075
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.537566
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.556972
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.579981
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.607706
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.641489
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.681134
