name: code_filter
text_field: text
pipeline:
    - name: text_len_filter
      kwargs:
          text_field: text
          lower_bound: 32 # 2 ** 5
          upper_bound: 262144 # 2 ** 18
    - name: float_filter  # p5
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.337761
    - name: float_filter  # p10
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.385466
    - name: float_filter  # p15
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.413040
    - name: float_filter  # p20
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.432766
    - name: float_filter  # p25
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.448815
    - name: float_filter  # p30
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.462474
    - name: float_filter  # p35
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.474751
    - name: float_filter  # p40
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.485599
    - name: float_filter  # p45
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.495316
    - name: float_filter  # p50
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.504472
    - name: float_filter  # p55
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.514328
    - name: float_filter  # p60
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.524605
    - name: float_filter  # p65
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.536271
    - name: float_filter  # p70
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.549474
    - name: float_filter  # p75
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.564354
    - name: float_filter  # p80
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.582288
    - name: float_filter  # p85
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.603281
    - name: float_filter  # p90
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.629758
    - name: float_filter  # p95
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.665426
