name: code_filter
text_field: text
pipeline:
    - name: text_len_filter # p1-p99
      step: invalid_length
      kwargs:
          text_field: text
          lower_bound: 10
          upper_bound: 27118
    - name: float_filter # p5
      step: quality_p05
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.024332
    - name: float_filter # p10
      step: quality_p10
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.062764
    - name: float_filter # p15
      step: quality_p15
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.121761
    - name: float_filter # p20
      step: quality_p20
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.164162
    - name: float_filter # p25
      step: quality_p25
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.196182
    - name: float_filter # p30
      step: quality_p30
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.222318
    - name: float_filter # p35
      step: quality_p35
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.241030
    - name: float_filter # p40
      step: quality_p40
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.253893
    - name: float_filter # p45
      step: quality_p45
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.262138
    - name: float_filter # p50
      step: quality_p50
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.271665
    - name: float_filter # p55
      step: quality_p55
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.281228
    - name: float_filter # p60
      step: quality_p60
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.291113
    - name: float_filter # p65
      step: quality_p65
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.300766
    - name: float_filter # p70
      step: quality_p70
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.311136
    - name: float_filter # p75
      step: quality_p75
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.321653
    - name: float_filter # p80
      step: quality_p80
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.333544
    - name: float_filter # p85
      step: quality_p85
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.347081
    - name: float_filter # p90
      step: quality_p90
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.363194
    - name: float_filter # p95
      step: quality_p95
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.387566
