name: code_filter
text_field: text
pipeline:
  - name: text_len_filter
    kwargs:
      text_field: text
      lower_bound: 47
      upper_bound: 31582
  - name: float_filter
    kwargs:
      float_field: metadata.code_quality.__label__pos
      lower_bound: 0.128016
