name: code_filter
text_field: text
pipeline:
    - name: text_len_filter
      kwargs:
          text_field: text
          lower_bound: 32 # 2 ** 5
          upper_bound: 262144 # 2 ** 18
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.235847
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.252451
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.253556
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.253693
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.253801
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.255152
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.259726
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.270152
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.289552
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.319922
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.358941
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.399600
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.435086
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.462614
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.482262
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.495260
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.513409
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.542017
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.592017
