name: code_filter
text_field: text
pipeline:
    - name: text_len_filter  # p1-p99
      kwargs:
          text_field: text
          lower_bound: 49
          upper_bound: 17047
    - name: float_filter  # p5
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.290992
    - name: float_filter  # p10
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.319163
    - name: float_filter  # p15
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.341288
    - name: float_filter  # p20
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.360438
    - name: float_filter  # p25
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.377776
    - name: float_filter  # p30
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.394091
    - name: float_filter  # p35
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.409967
    - name: float_filter  # p40
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.425537
    - name: float_filter  # p45
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.441358
    - name: float_filter  # p50
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.457648
    - name: float_filter  # p55
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.474245
    - name: float_filter  # p60
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.490535
    - name: float_filter  # p65
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.506174
    - name: float_filter  # p70
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.522855
    - name: float_filter  # p75
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.541767
    - name: float_filter  # p80
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.563023
    - name: float_filter  # p85
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.587806
    - name: float_filter  # p90
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.617969
    - name: float_filter  # p95
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.656724
