name: code_filter
text_field: text
pipeline:
- name: text_len_filter
  step: invalid_length
  kwargs:
    text_field: text
    lower_bound: 49
    upper_bound: 17047
- name: float_filter
  step: quality_p00
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.290992
- name: float_filter
  step: quality_p05
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.319163
- name: float_filter
  step: quality_p10
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.341288
- name: float_filter
  step: quality_p15
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.360438
- name: float_filter
  step: quality_p20
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.377776
- name: float_filter
  step: quality_p25
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.394091
- name: float_filter
  step: quality_p30
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.409967
- name: float_filter
  step: quality_p35
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.425537
- name: float_filter
  step: quality_p40
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.441358
- name: float_filter
  step: quality_p45
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.457648
- name: float_filter
  step: quality_p50
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.474245
- name: float_filter
  step: quality_p55
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.490535
- name: float_filter
  step: quality_p60
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.506174
- name: float_filter
  step: quality_p65
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.522855
- name: float_filter
  step: quality_p70
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.541767
- name: float_filter
  step: quality_p75
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.563023
- name: float_filter
  step: quality_p80
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.587806
- name: float_filter
  step: quality_p85
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.617969
- name: float_filter
  step: quality_p90
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    lower_bound: 0.656724
- name: float_filter
  step: quality_p95
  kwargs:
    float_field: metadata.stack_edu_redux_combined
    upper_bound: 1000
