name: code_filter
text_field: text
pipeline:
    - name: text_len_filter
      kwargs:
          text_field: text
          lower_bound: 32 # 2 ** 5
          upper_bound: 262144 # 2 ** 18
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.260114
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.263523
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.271959
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.283006
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.295679
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.309249
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.323152
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.337196
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.351564
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.366482
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.382305
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.399444
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.418618
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.440571
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.465792
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.492335
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.522546
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.563088
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.622123
