name: code_classifier
text_field: text
pipeline:
    - name: ultrafineweb_annotator
      kwargs:
          text_field: text
          output_field: metadata.code_quality_auto5
          max_text_length: 10000
          fast_text_file: /mnt/raid0/ai2-llm/classifiers/code-quality/trained_models/fasttext/the-stack-v2_spring2code_v2_minhash_v2_annotated_sample_1GB_countup_criteria_v2_gpt-5-mini_10k_trimmed_fasttext_ultrafine_auto5/Python/model.bin
    - name: linear_transform_annotator
      features:
          - field: metadata.code_quality_auto5.__label__bin_0
            weight: -0.288666
          - field: metadata.code_quality_auto5.__label__bin_1
            weight: -0.066356
          - field: metadata.code_quality_auto5.__label__bin_2
            weight: 0.092443
          - field: metadata.code_quality_auto5.__label__bin_3
            weight: 0.024282
          - field: metadata.code_quality_auto5.__label__bin_4
            weight: 0.238178
      bias: 0.530797
      output_field: metadata.code_quality_auto5_combined
