name: code_filter
text_field: text
pipeline:
    # - name: text_len_filter
    #   kwargs:
    #       text_field: text
    #       lower_bound: 32 # 2 ** 5
    #       upper_bound: 262144 # 2 ** 18
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.269281
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.320058
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.347250
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.364456
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.376891
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.386392
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.394080
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.400733
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.406367
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.411806
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.417392
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.422810
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.427786
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.432193
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.437451
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.442792
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.449421
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.457665
    - name: float_filter
      kwargs:
          float_field: metadata.code_quality_multilabel_combined
          lower_bound: 0.469080
